export const COLORS = {
  TRANSPARENT: 'transparent',
  BLACK: '#1A1A1A',
  GRAY: 'gray',
  DEFAULT_BACKGROUND: '#F0F0F0',

  //CSV Accent Colors
  WHITE: '#FFFFFF',
  MIDNIGHT_BLUE: '#000048',
  DARK_BLUE: '#2F78C4',
  MEDIUM_BLUE: '#6AA2DC',
  LIGHT_BLUE: '#92BBE6',
  DARK_PLUM: '#2E308E',
  MEDIUM_PLUM: '#7373D8',
  LIGHT_PLUM: '#85A0F9',
  DARK_TEAL: '#06C7CC',
  MEDIUM_TEAL: '#26EFE9',
  LIGHT_TEAL: '#97F5F7',

  //CSV Neutral Colors
  VERY_DARK_GRAY: '#3D3D3D',
  DARK_GRAY: '#53565A',
  MEDIUM_GRAY: '#97999B',
  LIGHT_GRAY: '#D0D0CE',
  VERY_LIGHT_GRAY: '#EFEFEE',
  ULTRA_LIGHT_GRAY: '#F6F6F5',

  //CSV Highlight Colors
  HIGHLIGHT_RED: '#B81F2D',
  HIGHLIGHT_YELLOW: '#E9C71D',

  // Skill COLORS:
  AMERICAN_RED: '#B52E31',
  SKY_BLUE: '#61DBFB',
  MINT_GREEN: '#41B883',
  MINION_YELLOW: '#F0DB4F',
  JAVA_ORANGE: '#f89820',
};

export const GRADIENT = {
  light_theme: [COLORS.DARK_PLUM, COLORS.DARK_BLUE, COLORS.MEDIUM_BLUE],
  dark_theme: [COLORS.DARK_BLUE, COLORS.MEDIUM_BLUE, COLORS.LIGHT_BLUE],
};
