export enum Query {
  GetCommunity = 'community',
  GetCommunities = 'communities',
  GetCommunityJobLevels = 'communityJobLevels',
  GetCommunitiesWithPercentage = 'communitiesWithPercentage',
  GetManagers = 'managers',
  GetCommunityManagers = 'communityManagers',
  GetCommunityWithMembers = 'communityWithMembers',
  GetPeople = 'people',
  GetPeopleWorkState = 'peopleWorkState',
  GetPerson = 'person',
  GetPersonByCsvEmail = 'personByCsvEmail',
  GetPeopleBySkills = 'peopleBySkills',
  GetPeopleDetails = 'peopleDetails',
  GetPeopleDetailsDescription = 'peopleDetailsDescription',
  GetPeopleSkills = 'peopleSkills',
}
